name: fluttercontactpicker
description: Use Androids' and iOS' native contact pickers to chose phone numbers and email addresses from contacts of the users address book
version: 3.2.0-nullsafety.2
homepage: https://github.com/DRSchlaubi/contact_picker

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-3.0.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  contact_picker_platform_interface:
    git:
      url: https://github.com/niggelgame/contact_picker.git
      ref: feature/null_safety
      path: contact_picker_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.schlaubi.fluttercontactpicker
        pluginClass: FlutterContactPickerPlugin
      ios:
        pluginClass: FlutterContactPickerPlugin
